export interface F1Race {
  round: number;
  name: string;
  circuit: string;
  location: string;
  country: string;
  countryCode: string;
  startDate: string;
  endDate: string;
}

export type F1Series = "f1" | "f2" | "f3";

export const f1Calendar: F1Race[] = [
  {
    round: 1,
    name: "Australian Grand Prix",
    circuit: "Albert Park Circuit",
    location: "Melbourne",
    country: "Australia",
    countryCode: "AU",
    startDate: "2026-03-06",
    endDate: "2026-03-08",
  },
  {
    round: 2,
    name: "Chinese Grand Prix",
    circuit: "Shanghai International Circuit",
    location: "Shanghai",
    country: "China",
    countryCode: "CN",
    startDate: "2026-03-13",
    endDate: "2026-03-15",
  },
  {
    round: 3,
    name: "Japanese Grand Prix",
    circuit: "Suzuka Circuit",
    location: "Suzuka",
    country: "Japan",
    countryCode: "JP",
    startDate: "2026-03-27",
    endDate: "2026-03-29",
  },
  {
    round: 4,
    name: "Bahrain Grand Prix",
    circuit: "Bahrain International Circuit",
    location: "Sakhir",
    country: "Bahrain",
    countryCode: "BH",
    startDate: "2026-04-10",
    endDate: "2026-04-12",
  },
  {
    round: 5,
    name: "Saudi Arabian Grand Prix",
    circuit: "Jeddah Corniche Circuit",
    location: "Jeddah",
    country: "Saudi Arabia",
    countryCode: "SA",
    startDate: "2026-04-17",
    endDate: "2026-04-19",
  },
  {
    round: 6,
    name: "Miami Grand Prix",
    circuit: "Miami International Autodrome",
    location: "Miami",
    country: "United States",
    countryCode: "US",
    startDate: "2026-05-01",
    endDate: "2026-05-03",
  },
  {
    round: 7,
    name: "Emilia-Romagna Grand Prix",
    circuit: "Imola Circuit",
    location: "Imola",
    country: "Italy",
    countryCode: "IT",
    startDate: "2026-05-22",
    endDate: "2026-05-24",
  },
  {
    round: 8,
    name: "Monaco Grand Prix",
    circuit: "Circuit de Monaco",
    location: "Monte Carlo",
    country: "Monaco",
    countryCode: "MC",
    startDate: "2026-06-04",
    endDate: "2026-06-07",
  },
  {
    round: 9,
    name: "Spanish Grand Prix",
    circuit: "Circuit de Barcelona-Catalunya",
    location: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    startDate: "2026-06-12",
    endDate: "2026-06-14",
  },
  {
    round: 10,
    name: "Canadian Grand Prix",
    circuit: "Circuit Gilles-Villeneuve",
    location: "Montreal",
    country: "Canada",
    countryCode: "CA",
    startDate: "2026-06-26",
    endDate: "2026-06-28",
  },
  {
    round: 11,
    name: "Austrian Grand Prix",
    circuit: "Red Bull Ring",
    location: "Spielberg",
    country: "Austria",
    countryCode: "AT",
    startDate: "2026-07-03",
    endDate: "2026-07-05",
  },
  {
    round: 12,
    name: "British Grand Prix",
    circuit: "Silverstone Circuit",
    location: "Silverstone",
    country: "United Kingdom",
    countryCode: "GB",
    startDate: "2026-07-17",
    endDate: "2026-07-19",
  },
  {
    round: 13,
    name: "Belgian Grand Prix",
    circuit: "Circuit de Spa-Francorchamps",
    location: "Spa",
    country: "Belgium",
    countryCode: "BE",
    startDate: "2026-07-24",
    endDate: "2026-07-26",
  },
  {
    round: 14,
    name: "Hungarian Grand Prix",
    circuit: "Hungaroring",
    location: "Mogyoród",
    country: "Hungary",
    countryCode: "HU",
    startDate: "2026-07-31",
    endDate: "2026-08-02",
  },
  {
    round: 15,
    name: "Dutch Grand Prix",
    circuit: "Circuit Zandvoort",
    location: "Zandvoort",
    country: "Netherlands",
    countryCode: "NL",
    startDate: "2026-08-21",
    endDate: "2026-08-23",
  },
  {
    round: 16,
    name: "Italian Grand Prix",
    circuit: "Monza Circuit",
    location: "Monza",
    country: "Italy",
    countryCode: "IT",
    startDate: "2026-09-04",
    endDate: "2026-09-06",
  },
  {
    round: 17,
    name: "Azerbaijan Grand Prix",
    circuit: "Baku City Circuit",
    location: "Baku",
    country: "Azerbaijan",
    countryCode: "AZ",
    startDate: "2026-09-18",
    endDate: "2026-09-20",
  },
  {
    round: 18,
    name: "Singapore Grand Prix",
    circuit: "Marina Bay Street Circuit",
    location: "Singapore",
    country: "Singapore",
    countryCode: "SG",
    startDate: "2026-10-09",
    endDate: "2026-10-11",
  },
  {
    round: 19,
    name: "United States Grand Prix",
    circuit: "Circuit of the Americas",
    location: "Austin",
    country: "United States",
    countryCode: "US",
    startDate: "2026-10-23",
    endDate: "2026-10-25",
  },
  {
    round: 20,
    name: "Mexico City Grand Prix",
    circuit: "Autódromo Hermanos Rodríguez",
    location: "Mexico City",
    country: "Mexico",
    countryCode: "MX",
    startDate: "2026-10-30",
    endDate: "2026-11-01",
  },
  {
    round: 21,
    name: "São Paulo Grand Prix",
    circuit: "Interlagos Circuit",
    location: "São Paulo",
    country: "Brazil",
    countryCode: "BR",
    startDate: "2026-11-06",
    endDate: "2026-11-08",
  },
  {
    round: 22,
    name: "Las Vegas Grand Prix",
    circuit: "Las Vegas Street Circuit",
    location: "Las Vegas",
    country: "United States",
    countryCode: "US",
    startDate: "2026-11-19",
    endDate: "2026-11-21",
  },
  {
    round: 23,
    name: "Qatar Grand Prix",
    circuit: "Lusail International Circuit",
    location: "Lusail",
    country: "Qatar",
    countryCode: "QA",
    startDate: "2026-11-27",
    endDate: "2026-11-29",
  },
  {
    round: 24,
    name: "Abu Dhabi Grand Prix",
    circuit: "Yas Marina Circuit",
    location: "Abu Dhabi",
    country: "United Arab Emirates",
    countryCode: "AE",
    startDate: "2026-12-04",
    endDate: "2026-12-06",
  },
];

export const f2Calendar: F1Race[] = [
  {
    round: 1,
    name: "Australian Grand Prix",
    circuit: "Albert Park Circuit",
    location: "Melbourne",
    country: "Australia",
    countryCode: "AU",
    startDate: "2026-03-06",
    endDate: "2026-03-08",
  },
  {
    round: 2,
    name: "Miami Grand Prix",
    circuit: "Miami International Autodrome",
    location: "Miami",
    country: "United States",
    countryCode: "US",
    startDate: "2026-05-01",
    endDate: "2026-05-03",
  },
  {
    round: 3,
    name: "Canadian Grand Prix",
    circuit: "Circuit Gilles-Villeneuve",
    location: "Montreal",
    country: "Canada",
    countryCode: "CA",
    startDate: "2026-05-22",
    endDate: "2026-05-24",
  },
  {
    round: 4,
    name: "Monaco Grand Prix",
    circuit: "Circuit de Monaco",
    location: "Monte Carlo",
    country: "Monaco",
    countryCode: "MC",
    startDate: "2026-06-04",
    endDate: "2026-06-07",
  },
  {
    round: 5,
    name: "Spanish Grand Prix",
    circuit: "Circuit de Barcelona-Catalunya",
    location: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    startDate: "2026-06-12",
    endDate: "2026-06-14",
  },
  {
    round: 6,
    name: "Austrian Grand Prix",
    circuit: "Red Bull Ring",
    location: "Spielberg",
    country: "Austria",
    countryCode: "AT",
    startDate: "2026-06-26",
    endDate: "2026-06-28",
  },
  {
    round: 7,
    name: "British Grand Prix",
    circuit: "Silverstone Circuit",
    location: "Silverstone",
    country: "United Kingdom",
    countryCode: "GB",
    startDate: "2026-07-03",
    endDate: "2026-07-05",
  },
  {
    round: 8,
    name: "Belgian Grand Prix",
    circuit: "Circuit de Spa-Francorchamps",
    location: "Spa",
    country: "Belgium",
    countryCode: "BE",
    startDate: "2026-07-17",
    endDate: "2026-07-19",
  },
  {
    round: 9,
    name: "Hungarian Grand Prix",
    circuit: "Hungaroring",
    location: "Mogyoród",
    country: "Hungary",
    countryCode: "HU",
    startDate: "2026-07-24",
    endDate: "2026-07-26",
  },
  {
    round: 10,
    name: "Italian Grand Prix",
    circuit: "Monza Circuit",
    location: "Monza",
    country: "Italy",
    countryCode: "IT",
    startDate: "2026-09-04",
    endDate: "2026-09-06",
  },
  {
    round: 11,
    name: "Madrid Grand Prix",
    circuit: "Madrid Street Circuit",
    location: "Madrid",
    country: "Spain",
    countryCode: "ES",
    startDate: "2026-09-11",
    endDate: "2026-09-13",
  },
  {
    round: 12,
    name: "Azerbaijan Grand Prix",
    circuit: "Baku City Circuit",
    location: "Baku",
    country: "Azerbaijan",
    countryCode: "AZ",
    startDate: "2026-09-25",
    endDate: "2026-09-27",
  },
  {
    round: 13,
    name: "Qatar Grand Prix",
    circuit: "Lusail International Circuit",
    location: "Lusail",
    country: "Qatar",
    countryCode: "QA",
    startDate: "2026-11-27",
    endDate: "2026-11-29",
  },
  {
    round: 14,
    name: "Abu Dhabi Grand Prix",
    circuit: "Yas Marina Circuit",
    location: "Abu Dhabi",
    country: "United Arab Emirates",
    countryCode: "AE",
    startDate: "2026-12-04",
    endDate: "2026-12-06",
  },
];

export const f3Calendar: F1Race[] = [...f2Calendar];

export const seriesData: Record<
  F1Series,
  {
    label: string;
    fullLabel: string;
    calendar: F1Race[];
  }
> = {
  f1: {
    label: "F1",
    fullLabel: "Formula 1",
    calendar: f1Calendar,
  },
  f2: {
    label: "F2",
    fullLabel: "Formula 2",
    calendar: f2Calendar,
  },
  f3: {
    label: "F3",
    fullLabel: "Formula 3",
    calendar: f3Calendar,
  },
};
